/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RbacRouteImport } from './routes/rbac'
import { Route as ModulesRouteImport } from './routes/modules'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as BundlesRouteImport } from './routes/bundles'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompanyRegistrationRouteImport } from './routes/company.registration'
import { Route as CompanyListRouteImport } from './routes/company.list'
import { Route as CompaniesCompanyIdRouteImport } from './routes/companies.$companyId'
import { Route as BundlesBundleIdRouteImport } from './routes/bundles.$bundleId'
import { Route as AcceptInviteTokenRouteImport } from './routes/accept-invite.$token'

const RbacRoute = RbacRouteImport.update({
  id: '/rbac',
  path: '/rbac',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const BundlesRoute = BundlesRouteImport.update({
  id: '/bundles',
  path: '/bundles',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRegistrationRoute = CompanyRegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyListRoute = CompanyListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => CompanyRoute,
} as any)
const CompaniesCompanyIdRoute = CompaniesCompanyIdRouteImport.update({
  id: '/$companyId',
  path: '/$companyId',
  getParentRoute: () => CompaniesRoute,
} as any)
const BundlesBundleIdRoute = BundlesBundleIdRouteImport.update({
  id: '/$bundleId',
  path: '/$bundleId',
  getParentRoute: () => BundlesRoute,
} as any)
const AcceptInviteTokenRoute = AcceptInviteTokenRouteImport.update({
  id: '/accept-invite/$token',
  path: '/accept-invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bundles': typeof BundlesRouteWithChildren
  '/companies': typeof CompaniesRouteWithChildren
  '/company': typeof CompanyRouteWithChildren
  '/modules': typeof ModulesRoute
  '/rbac': typeof RbacRoute
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/bundles/$bundleId': typeof BundlesBundleIdRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/company/list': typeof CompanyListRoute
  '/company/registration': typeof CompanyRegistrationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bundles': typeof BundlesRouteWithChildren
  '/companies': typeof CompaniesRouteWithChildren
  '/company': typeof CompanyRouteWithChildren
  '/modules': typeof ModulesRoute
  '/rbac': typeof RbacRoute
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/bundles/$bundleId': typeof BundlesBundleIdRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/company/list': typeof CompanyListRoute
  '/company/registration': typeof CompanyRegistrationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bundles': typeof BundlesRouteWithChildren
  '/companies': typeof CompaniesRouteWithChildren
  '/company': typeof CompanyRouteWithChildren
  '/modules': typeof ModulesRoute
  '/rbac': typeof RbacRoute
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/bundles/$bundleId': typeof BundlesBundleIdRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/company/list': typeof CompanyListRoute
  '/company/registration': typeof CompanyRegistrationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bundles'
    | '/companies'
    | '/company'
    | '/modules'
    | '/rbac'
    | '/accept-invite/$token'
    | '/bundles/$bundleId'
    | '/companies/$companyId'
    | '/company/list'
    | '/company/registration'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bundles'
    | '/companies'
    | '/company'
    | '/modules'
    | '/rbac'
    | '/accept-invite/$token'
    | '/bundles/$bundleId'
    | '/companies/$companyId'
    | '/company/list'
    | '/company/registration'
  id:
    | '__root__'
    | '/'
    | '/bundles'
    | '/companies'
    | '/company'
    | '/modules'
    | '/rbac'
    | '/accept-invite/$token'
    | '/bundles/$bundleId'
    | '/companies/$companyId'
    | '/company/list'
    | '/company/registration'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BundlesRoute: typeof BundlesRouteWithChildren
  CompaniesRoute: typeof CompaniesRouteWithChildren
  CompanyRoute: typeof CompanyRouteWithChildren
  ModulesRoute: typeof ModulesRoute
  RbacRoute: typeof RbacRoute
  AcceptInviteTokenRoute: typeof AcceptInviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rbac': {
      id: '/rbac'
      path: '/rbac'
      fullPath: '/rbac'
      preLoaderRoute: typeof RbacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules': {
      id: '/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundles': {
      id: '/bundles'
      path: '/bundles'
      fullPath: '/bundles'
      preLoaderRoute: typeof BundlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/registration': {
      id: '/company/registration'
      path: '/registration'
      fullPath: '/company/registration'
      preLoaderRoute: typeof CompanyRegistrationRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/company/list': {
      id: '/company/list'
      path: '/list'
      fullPath: '/company/list'
      preLoaderRoute: typeof CompanyListRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/companies/$companyId': {
      id: '/companies/$companyId'
      path: '/$companyId'
      fullPath: '/companies/$companyId'
      preLoaderRoute: typeof CompaniesCompanyIdRouteImport
      parentRoute: typeof CompaniesRoute
    }
    '/bundles/$bundleId': {
      id: '/bundles/$bundleId'
      path: '/$bundleId'
      fullPath: '/bundles/$bundleId'
      preLoaderRoute: typeof BundlesBundleIdRouteImport
      parentRoute: typeof BundlesRoute
    }
    '/accept-invite/$token': {
      id: '/accept-invite/$token'
      path: '/accept-invite/$token'
      fullPath: '/accept-invite/$token'
      preLoaderRoute: typeof AcceptInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BundlesRouteChildren {
  BundlesBundleIdRoute: typeof BundlesBundleIdRoute
}

const BundlesRouteChildren: BundlesRouteChildren = {
  BundlesBundleIdRoute: BundlesBundleIdRoute,
}

const BundlesRouteWithChildren =
  BundlesRoute._addFileChildren(BundlesRouteChildren)

interface CompaniesRouteChildren {
  CompaniesCompanyIdRoute: typeof CompaniesCompanyIdRoute
}

const CompaniesRouteChildren: CompaniesRouteChildren = {
  CompaniesCompanyIdRoute: CompaniesCompanyIdRoute,
}

const CompaniesRouteWithChildren = CompaniesRoute._addFileChildren(
  CompaniesRouteChildren,
)

interface CompanyRouteChildren {
  CompanyListRoute: typeof CompanyListRoute
  CompanyRegistrationRoute: typeof CompanyRegistrationRoute
}

const CompanyRouteChildren: CompanyRouteChildren = {
  CompanyListRoute: CompanyListRoute,
  CompanyRegistrationRoute: CompanyRegistrationRoute,
}

const CompanyRouteWithChildren =
  CompanyRoute._addFileChildren(CompanyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BundlesRoute: BundlesRouteWithChildren,
  CompaniesRoute: CompaniesRouteWithChildren,
  CompanyRoute: CompanyRouteWithChildren,
  ModulesRoute: ModulesRoute,
  RbacRoute: RbacRoute,
  AcceptInviteTokenRoute: AcceptInviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
