/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as RbacRouteImport } from './routes/rbac'
import { Route as ModulesRouteImport } from './routes/modules'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as BundlesRouteImport } from './routes/bundles'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompaniesCompanyIdRouteImport } from './routes/companies.$companyId'
import { Route as BundlesBundleIdRouteImport } from './routes/bundles.$bundleId'
import { Route as AcceptInviteTokenRouteImport } from './routes/accept-invite.$token'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const RbacRoute = RbacRouteImport.update({
  id: '/rbac',
  path: '/rbac',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const BundlesRoute = BundlesRouteImport.update({
  id: '/bundles',
  path: '/bundles',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesCompanyIdRoute = CompaniesCompanyIdRouteImport.update({
  id: '/$companyId',
  path: '/$companyId',
  getParentRoute: () => CompaniesRoute,
} as any)
const BundlesBundleIdRoute = BundlesBundleIdRouteImport.update({
  id: '/$bundleId',
  path: '/$bundleId',
  getParentRoute: () => BundlesRoute,
} as any)
const AcceptInviteTokenRoute = AcceptInviteTokenRouteImport.update({
  id: '/accept-invite/$token',
  path: '/accept-invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bundles': typeof BundlesRouteWithChildren
  '/companies': typeof CompaniesRouteWithChildren
  '/modules': typeof ModulesRoute
  '/rbac': typeof RbacRoute
  '/templates': typeof TemplatesRoute
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/bundles/$bundleId': typeof BundlesBundleIdRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bundles': typeof BundlesRouteWithChildren
  '/companies': typeof CompaniesRouteWithChildren
  '/modules': typeof ModulesRoute
  '/rbac': typeof RbacRoute
  '/templates': typeof TemplatesRoute
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/bundles/$bundleId': typeof BundlesBundleIdRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bundles': typeof BundlesRouteWithChildren
  '/companies': typeof CompaniesRouteWithChildren
  '/modules': typeof ModulesRoute
  '/rbac': typeof RbacRoute
  '/templates': typeof TemplatesRoute
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/bundles/$bundleId': typeof BundlesBundleIdRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bundles'
    | '/companies'
    | '/modules'
    | '/rbac'
    | '/templates'
    | '/accept-invite/$token'
    | '/bundles/$bundleId'
    | '/companies/$companyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bundles'
    | '/companies'
    | '/modules'
    | '/rbac'
    | '/templates'
    | '/accept-invite/$token'
    | '/bundles/$bundleId'
    | '/companies/$companyId'
  id:
    | '__root__'
    | '/'
    | '/bundles'
    | '/companies'
    | '/modules'
    | '/rbac'
    | '/templates'
    | '/accept-invite/$token'
    | '/bundles/$bundleId'
    | '/companies/$companyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BundlesRoute: typeof BundlesRouteWithChildren
  CompaniesRoute: typeof CompaniesRouteWithChildren
  ModulesRoute: typeof ModulesRoute
  RbacRoute: typeof RbacRoute
  TemplatesRoute: typeof TemplatesRoute
  AcceptInviteTokenRoute: typeof AcceptInviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rbac': {
      id: '/rbac'
      path: '/rbac'
      fullPath: '/rbac'
      preLoaderRoute: typeof RbacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules': {
      id: '/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundles': {
      id: '/bundles'
      path: '/bundles'
      fullPath: '/bundles'
      preLoaderRoute: typeof BundlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$companyId': {
      id: '/companies/$companyId'
      path: '/$companyId'
      fullPath: '/companies/$companyId'
      preLoaderRoute: typeof CompaniesCompanyIdRouteImport
      parentRoute: typeof CompaniesRoute
    }
    '/bundles/$bundleId': {
      id: '/bundles/$bundleId'
      path: '/$bundleId'
      fullPath: '/bundles/$bundleId'
      preLoaderRoute: typeof BundlesBundleIdRouteImport
      parentRoute: typeof BundlesRoute
    }
    '/accept-invite/$token': {
      id: '/accept-invite/$token'
      path: '/accept-invite/$token'
      fullPath: '/accept-invite/$token'
      preLoaderRoute: typeof AcceptInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BundlesRouteChildren {
  BundlesBundleIdRoute: typeof BundlesBundleIdRoute
}

const BundlesRouteChildren: BundlesRouteChildren = {
  BundlesBundleIdRoute: BundlesBundleIdRoute,
}

const BundlesRouteWithChildren =
  BundlesRoute._addFileChildren(BundlesRouteChildren)

interface CompaniesRouteChildren {
  CompaniesCompanyIdRoute: typeof CompaniesCompanyIdRoute
}

const CompaniesRouteChildren: CompaniesRouteChildren = {
  CompaniesCompanyIdRoute: CompaniesCompanyIdRoute,
}

const CompaniesRouteWithChildren = CompaniesRoute._addFileChildren(
  CompaniesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BundlesRoute: BundlesRouteWithChildren,
  CompaniesRoute: CompaniesRouteWithChildren,
  ModulesRoute: ModulesRoute,
  RbacRoute: RbacRoute,
  TemplatesRoute: TemplatesRoute,
  AcceptInviteTokenRoute: AcceptInviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
